variables:
    PROJECT_DIR: "vivado"
    VIVADO_PATH: "/opt/Xilinx/Vivado/2018.3/bin/vivado"
    PROJECT_NAME: "thinpad_top"

stages:
  - build
  - test

before_script:
    - cd ${PROJECT_DIR}

bitstream:
  stage: build
  tags:
    - vivado
  image: vivado2018:2018.3
  script:
    - env
    - ${VIVADO_PATH} -mode tcl -source scripts/build.tcl ${PROJECT_NAME}.xpr

  artifacts:
    paths:
      - ${PROJECT_DIR}/thinpad_top.runs/impl_1/thinpad_top.bit
      - ${PROJECT_DIR}/thinpad_top.runs/impl_1/runme.log
      - ${PROJECT_DIR}/thinpad_top.runs/synth_1/runme.log

sonar-scanner:
  image: harryleafchen/debian-curl-tar
  stage: test
  tags:
    - secoder
  script:
    - curl -s "http://10.0.0.11/sonar-scanner.tar.gz" -o "/tmp/sonar-scanner.tar.gz"
    - tar -xf "/tmp/sonar-scanner.tar.gz" -C /tmp
    - /tmp/sonar-scanner/bin/sonar-scanner
