variables:
    PROJECT_DIR: "vivado"
    VIVADO_PATH: "/opt/Xilinx/Vivado/2018.3/bin/vivado"
    PROJECT_NAME: "intomips"
    

stages:
  - run_simulation
  - build
  - test

before_script:
    - cd ${PROJECT_DIR}



# from https://github.com/trivialmips/TrivialMIPS/blob/master/.gitlab-ci.yml
run_all_testbenches:
  image: vivado2018:2018.3
  tags:
    - vivado
  stage: run_simulation
  script:
    - export SIMULATION=sim_1
    - ${VIVADO_PATH} -mode tcl -source scripts/run_simulation.tcl ${PROJECT_NAME}.xpr
    - bash scripts/check_simulation.sh
  artifacts:
    paths:
      - ${PROJECT_DIR}/${PROJECT_NAME}.sim/*/behav/xsim/simulate.log
    when: always


bitstream:
  stage: build
  tags:
    - vivado
  image: vivado2018:2018.3
  script:
    - env
    - ${VIVADO_PATH} -mode tcl -source scripts/build.tcl ${PROJECT_NAME}.xpr

  artifacts:
    paths:
      - ${PROJECT_DIR}/$(PROJECT_NAME).runs/impl_1/$(PROJECT_NAME).bit
      - ${PROJECT_DIR}/$(PROJECT_NAME).runs/impl_1/runme.log
      - ${PROJECT_DIR}/$(PROJECT_NAME).runs/synth_1/runme.log



sonar-scanner:
  image: harryleafchen/debian-curl-tar
  stage: test
  tags:
    - secoder
  script:
    - curl -s "http://10.0.0.11/sonar-scanner.tar.gz" -o "/tmp/sonar-scanner.tar.gz"
    - tar -xf "/tmp/sonar-scanner.tar.gz" -C /tmp
    - /tmp/sonar-scanner/bin/sonar-scanner
